apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: worker-controller
build:
  tagPolicy:
    gitCommit:
      variant: CommitSha
      ignoreChanges: true
profiles:
  - name: helloworld
    build:
      artifacts:
        - image: helloworld
          context: internal/demo
          docker:
            dockerfile: Dockerfile
            buildArgs:
              DD_GIT_COMMIT_SHA: "{{ .IMAGE_TAG }}"
              DD_GIT_REPOSITORY_URL: "github.com/temporalio/temporal-worker-controller"
              WORKER: "helloworld"
    manifests:
      rawYaml:
        - internal/demo/helloworld/temporal_worker_deployment.yaml
deploy:
  kubeContext: minikube
  kubectl: {}
resourceSelector:
  allow:
    - groupKind: "TemporalWorkerDeployment.temporal.io"
      image: [".*"]
