# permissions for end users to edit temporalworkerdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: temporalworkerdeployment-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: worker-controller
    app.kubernetes.io/part-of: worker-controller
    app.kubernetes.io/managed-by: kustomize
  name: temporalworkerdeployment-editor-role
rules:
- apiGroups:
  - temporal.io
  resources:
  - temporalworkerdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - temporal.io
  resources:
  - temporalworkerdeployments/status
  verbs:
  - get
